FROM alpine:3.7

VOLUME /app/src
WORKDIR /app/src/

RUN \
  apk update && \
  apk add \
    python3=3.6.3-r9 postgresql-dev=10.3-r0 gcc=6.4.0-r5 \
    python3-dev=3.6.3-r9 libc-dev=0.7.1-r0 libffi-dev=3.2.1-r4

COPY ./src/requirements.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
