version: "2"

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=password

  api:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - "./src:/app/src"
    depends_on:
      - postgres
    ports:
      - 8000:8000
    environment:
      - MJOE_DEBUG=1
      - MJOE_SECRET_KEY=6c68c570-6f43-4590-8c16-38a257f085ee
      - MJOE_DATABASE=postgres://postgres:password@postgres/postgres
      - PYTHONUNBUFFERED=1
