# Generated by Django 2.0.1 on 2018-01-26 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('household', '0001_initial'),
        ('currency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='')),
                ('creation_time', models.DateTimeField()),
                ('booking_time', models.DateTimeField()),
                ('valuta_time', models.DateTimeField()),
                ('value', models.PositiveIntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('credit_account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_journal_entries', to='account.Account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='currency.Currency')),
                ('debit_account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_journal_entries', to='account.Account')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='household.Household')),
            ],
            options={
                'verbose_name_plural': 'Journal entries',
            },
        ),
        migrations.CreateModel(
            name='JournalEntryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry_tags', to='journal.JournalEntry')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry_tags', to='tag.Tag')),
            ],
        ),
    ]
