# Generated by Django 2.0.1 on 2018-03-26 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField()),
                ('activation_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('ip', models.CharField(max_length=128)),
                ('code', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_activations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
