# Generated by Django 2.0.1 on 2018-01-25 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_currencies', to='geo.Country')),
            ],
            options={
                'verbose_name_plural': 'Country currencies',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=3, unique=True)),
                ('symbol', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.AddField(
            model_name='countrycurrency',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_currencies', to='currency.Currency'),
        ),
    ]
